### PR TITLE
Add metal

### PR DESCRIPTION
**Pull request by bryceosterhaus**

### CODE REVIEW

**Comment by robframpton** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by robframpton** [comment]
Hey @bryceosterhaus,

I'm guessing 2e56534 is the only commit that matters here?

**Comment by bryceosterhaus** [comment]
Yeah I believe so

**Comment by bryceosterhaus** [comment]
why didnt u ever merge this?

**Comment by robframpton** [comment]
I do what I want.

**Pull request closed without merging**
